#
# docker-compose for vLLM inference service.
#
x-defaults: &defaults
  image: vllm/vllm-openai:latest-aarch64
  restart: unless-stopped
  network_mode: host
  volumes:
    - ~/.cache/huggingface:/root/.cache/huggingface
    - ~/.cache/vllm:/root/.cache/vllm

  env_file:
    - .env.vllm
  environment:
    CUTE_DSL_ARCH: sm_121a
    FLASHINFER_DISABLE_VERSION_CHECK: "1"
    VLLM_MARLIN_USE_ATOMIC_ADD: "1"
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  vllm-nv-qwen3.6-27B-NVFP4:
    profiles: [vllm-nv-qwen3.6-27B-NVFP4]
    container_name: vllm-nv-qwen3.6-27B-NVFP4
    <<: *defaults
    command: >
      ${MODEL_ID}
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size "1"
      --trust-remote-code
      --moe-backend marlin
      --kv-cache-dtype auto
      --gpu-memory-utilization "0.4"
      --max-model-len "262144"
      --max-num-batched-tokens "8192"
      --max-num-seqs "3"
      --enable-chunked-prefill
      --enable-prefix-caching
      --speculative-config '{"method":"mtp","num_speculative_tokens":3,"moe_backend":"triton"}'
      --load-format fastsafetensors
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --no-language-model-only
      --default-chat-template-kwargs '{"enable_thinking": true}'

  vllm-uns-qwen3.6-27B-NVFP4:
    profiles: [vllm-uns-qwen3.6-27B-NVFP4]
    container_name: vllm-uns-qwen3.6-27B-NVFP4
    <<: *defaults
    command: >
      ${MODEL_ID}
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size "1"
      --trust-remote-code
      --kv-cache-dtype auto
      --moe-backend flashinfer_b12x
      --linear-backend flashinfer_b12x
      --gpu-memory-utilization "0.4"
      --max-model-len "262144"
      --max-num-batched-tokens "8192"
      --max-num-seqs "3"
      --enable-chunked-prefill
      --enable-prefix-caching
      --speculative-config '{"method":"mtp","num_speculative_tokens":2}'
      --load-format fastsafetensors
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --no-language-model-only
      --default-chat-template-kwargs '{"enable_thinking": true}'

  vllm-nv-qwen3.6-35B-A3B-NVFP4:
    profiles: [vllm-nv-qwen3.6-35B-A3B-NVFP4]
    container_name: vllm-nv-qwen3.6-35B-A3B-NVFP4
    <<: *defaults
    command: >
      ${MODEL_ID}
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size "1"
      --trust-remote-code
      --kv-cache-dtype fp8
      --attention-backend flashinfer
      --moe-backend marlin
      --gpu-memory-utilization "0.4"
      --max-model-len "262144"
      --max-num-seqs "4"
      --max-num-batched-tokens "8192"
      --enable-chunked-prefill
      --enable-prefix-caching
      --async-scheduling
      --speculative-config '{"method":"mtp","num_speculative_tokens":3,"moe_backend":"triton"}'
      --load-format fastsafetensors
      --reasoning-parser qwen3
      --tool-call-parser qwen3_xml
      --enable-auto-tool-choice
      --no-language-model-only

  vllm-uns-qwen3.6-35B-A3B-NVFP4:
    profiles: [vllm-uns-qwen3.6-35B-A3B-NVFP4]
    container_name: vllm-uns-qwen3.6-35B-A3B-NVFP4
    <<: *defaults
    command: >
      ${MODEL_ID}
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size "1"
      --trust-remote-code
      --kv-cache-dtype auto
      --attention-backend flashinfer
      --moe-backend marlin
      --gpu-memory-utilization "0.4"
      --max-model-len "262144"
      --max-num-seqs "4"
      --max-num-batched-tokens "8192"
      --enable-chunked-prefill
      --enable-prefix-caching
      --speculative-config '{"method":"mtp","num_speculative_tokens":2}'
      --load-format fastsafetensors
      --reasoning-parser qwen3
      --tool-call-parser qwen3_xml
      --enable-auto-tool-choice
      --no-language-model-only

  vllm-uns-qwen3.6-35B-A3B-NVFP4-fast:
    profiles: [vllm-uns-qwen3.6-35B-A3B-NVFP4-fast]
    container_name: vllm-uns-qwen3.6-35B-A3B-NVFP4-fast
    <<: *defaults
    command: >
      ${MODEL_ID}
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size "1"
      --trust-remote-code
      --kv-cache-dtype auto
      --attention-backend flashinfer
      --moe-backend marlin
      --gpu-memory-utilization "0.4"
      --max-model-len "262144"
      --max-num-seqs "4"
      --max-num-batched-tokens "8192"
      --enable-chunked-prefill
      --enable-prefix-caching
      --speculative-config '{"method":"mtp","num_speculative_tokens":2}'
      --load-format fastsafetensors
      --reasoning-parser qwen3
      --tool-call-parser qwen3_xml
      --enable-auto-tool-choice
      --no-language-model-only

  prometheus:
    image: prom/prometheus:latest
    container_name: vllm-prometheus
    restart: unless-stopped
    network_mode: host
    # ports:
    #  - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: vllm-grafana
    restart: unless-stopped
    network_mode: host
    # ports:
    #  - "3000:3000"
    depends_on:
      - prometheus
    environment:
      GF_SERVER_HTTP_PORT: "3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
