global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm
    # Written by vllm-serve.sh start: localhost:8000 labelled with the Run.
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.json
